### ISSUE TITLE
SNC control plane replicas

### ISSUE THREAD

**Issue by bojanraic** [cragr/okd4_files#6]
Hi, 

In the snc branch, control plane replicas is set to 3.
```
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
```

Is this a typo/leftover from the main guide/branch?
Thanks!
